CREATE TABLE role(
    role_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL
)

CREATE TABLE user (
    user_id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    last_name text NOT NULL,
    first_name text NOT NULL,
    email text UNIQUE NOT NULL,
    role_id integer NOT NULL
        REFERENCES role(role_id)
        ON DELETE RESTRICT 
)
