
CREATE TABLE session (
    session_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token text NOT NULL UNIQUE,
    person_id int NOT NULL
        REFERENCES person(person_id)
        ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    expires_at timestamptz NOT NULL,
    is_revoked boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE person
    ADD COLUMN pass_hash text NOT NULL,
    ADD COLUMN is_deactivated boolean NOT NULL DEFAULT FALSE
;
