

CREATE TABLE organization (
    organization_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            text,
    point_value int
        -- this stores the value of points, for example, say one point is
        -- worth fifty cents then this would be 50 or if a point was worth 1
        -- cent then this would be 1 or if a point was worth $2 this would be 200
);

CREATE TABLE affiliation (
    person_id int NOT NULL
        REFERENCES person(person_id)
        ON DELETE CASCADE,
    organization_id int NOT NULL
        REFERENCES organization(organization_id)
        ON DELETE CASCADE,
    points int,

    PRIMARY KEY (person_id, organization_id)
);
