

CREATE TABLE organization (
    organization_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            text,
    conversion_rate int -- divide by 100 to get dollars/cents
);

CREATE TABLE affiliation (
    person_id int NOT NULL
        REFERENCES person(person_id)
        ON DELETE CASCADE,
    organization_id int NOT NULL
        REFERENCES organization(organization_id)
        ON DELETE CASCADE,
    points int,

    PRIMARY KEY (person_id, organization_id)
);
