trigger:
  - main
  - develop
  - feature/*
  - bugfix/*
  - hotfix/*
  - release/*

stages:
  - stage: Lint
    jobs:
      - job: LintGo
        displayName: Lint Go
        steps:
          - task: GoTool@0
            displayName: Install Go
            inputs:
              version: "1.15"
          - script: |
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
              sh -s -- -b $(go env GOPATH)/bin v1.35.2 && \
              echo '##vso[task.prependpath]$(HOME)/go/bin'
            displayName: Install golangci-lint
          - script: golangci-lint run
            workingDirectory: go/app
            displayName: Run golangci-lint

      - job: LintJS
        displayName: Lint JavaScript
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: Install Node.js
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | web/yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: web/node_modules
            displayName: Cache Node Modules (yarn)
          - script: yarn install
            workingDirectory: web
            displayName: Install Node packages (yarn)
          - script: npx eslint .
            workingDirectory: web
            displayName: Run eslint

      - job: LintPrettier
        displayName: Lint Prettier
        dependsOn: LintJS
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: Install Node.js
          # This step below counts on the fact that the LintJS job before it
          # will install all of the Node modules and load them into the cache.
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | web/yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: node_modules
            displayName: Cache Node Modules (yarn)
          - script: npx prettier --check .
            displayName: Check Prettier Compliance

  - stage: Test
    jobs:
      - job: TestGo
        displayName: Test Go
        steps:
          - task: GoTool@0
            displayName: Install Go
            inputs:
              version: "1.15"
          - task: Go@0
            displayName: Test Go
            inputs:
              command: "test"
              workingDirectory: go/app

  - stage: Build
    jobs:
      - job: BuildGo
        displayName: Build API Server (Go)
        steps:
          - task: GoTool@0
            displayName: Install Go
            inputs:
              version: "1.15"
          - task: Go@0
            displayName: Go Build
            inputs:
              command: "build"
              workingDirectory: go/app/cmd/api
          - publish: $(System.DefaultWorkingDirectory)/go/app/cmd/api/api
            artifact: APIServer

      - job: BuildJS
        displayName: Build React App (JS)
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: Install Node.js
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | web/yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: web/node_modules
            displayName: Cache Node Modules (yarn)
          - script: yarn install
            workingDirectory: web
            displayName: Install Node packages (yarn)
          - script: yarn build
            workingDirectory: web
            displayName: React Build
          - publish: $(System.DefaultWorkingDirectory)/web/build
            artifact: ReactApp

  # - stage: Deploy
