trigger:
  - main
  - develop
  - starter-pipeline
  - feature/*
  - bugfix/*
  - hotfix/*
  - release/*

stages:
  - stage: Lint
    jobs:
      - job: LintGo
        displayName: Lint Go
        steps:
          - task: GoTool@0
            displayName: Install Go
            inputs:
              version: "1.15"
          - script: |
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
              sh -s -- -b $(go env GOPATH)/bin v1.35.2 && \
              echo '##vso[task.prependpath]$(HOME)/go/bin'
            displayName: Install golangci-lint
          - script: golangci-lint run
            workingDirectory: go/demo
            displayName: Run golangci-lint

      # - job: LintJS
      #   displayName: Lint JavaScript
      #   steps:
      #     -

  - stage: Test
    jobs:
      - job: TestGo
        displayName: Test Go
        steps:
          - task: GoTool@0
            displayName: Install Go
            inputs:
              version: "1.15"
          - script: pwd && echo '' && ls
          - task: Go@0
            displayName: Test Go
            inputs:
              command: "test"
              workingDirectory: go/demo

  # - stage: Build

  # - stage: Deploy
